### ISSUE TITLE
battery_backlight > system76-backlight-manager-cli

### ISSUE THREAD

**Issue by yochananmarqos** [JeffLabonte/System76-Backlight-Manager-cli#1]
You forgot to change some things from to `battery_backlight` to `system76-backlight-manager-cli`. I would do a pull request, but there were a few things I wasn't sure about.

**Comment by JeffLabonte** [comment]
You can go ahead. I will review it! :)

**Comment by JeffLabonte** [comment]
I have made the fixes. Changed the name completely and fix paths in Makefile. Changed the name and tested it on my machine.

I am planning on bringing back the tests and add more to the code.
